# Generated by Django 5.0.2 on 2024-07-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_shop_sizes_news_views_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
